/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { animated, useSpring } from "@react-spring/three";
import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";

import { Candy } from "./Candy";
import { hawkinsMaterials } from "@/utlis/hawkinsmaterials";

export default function Cannon(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/springAnimationModel/cannon-mobile/model.gltf");

  const { cannonScale, candyZ, candyOpacity } = useSpring({
    from: {
      cannonScale: 1,
      candyZ: 0,
      candyOpacity: 1,
    },
    to: [
      {
        cannonScale: 1.5,
        candyOpacity: 1,
      },
      {
        cannonScale: 1,
        candyZ: -4,
        candyOpacity: 1,
      },
    ],
    config: {
      mass: 5,
      tension: 400,
      friction: 50,
    },
    loop: true,
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, 0]}>
        <mesh geometry={nodes.cannonMobile_8angles_1.geometry}>
          <meshStandardMaterial {...hawkinsMaterials.brown} />
        </mesh>
        <mesh geometry={nodes.cannonMobile_8angles_2.geometry}>
          <meshStandardMaterial {...hawkinsMaterials.brown} />
        </mesh>
        <group position={[-0.22, 0.13, 0.26]}>
          <mesh geometry={nodes.wheel_backLeft_1.geometry}>
            <meshStandardMaterial {...hawkinsMaterials.metal} />
          </mesh>
          <mesh geometry={nodes.wheel_backLeft_2.geometry}>
            <meshStandardMaterial {...hawkinsMaterials.brown} />
          </mesh>
        </group>
        <group position={[0.22, 0.13, 0.26]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.wheel_backLeft_1.geometry}>
            <meshStandardMaterial {...hawkinsMaterials.metal} />
          </mesh>
          <mesh geometry={nodes.wheel_backLeft_2.geometry}>
            <meshStandardMaterial {...hawkinsMaterials.brown} />
          </mesh>
        </group>
        <group position={[-0.22, 0.13, -0.2]}>
          <mesh geometry={nodes.wheel_backLeft_1.geometry}>
            <meshStandardMaterial {...hawkinsMaterials.metal} />
          </mesh>
          <mesh geometry={nodes.wheel_backLeft_2.geometry}>
            <meshStandardMaterial {...hawkinsMaterials.brown} />
          </mesh>
        </group>
        <group position={[0.22, 0.13, -0.2]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.wheel_backLeft_1.geometry}>
            <meshStandardMaterial {...hawkinsMaterials.metal} />
          </mesh>
          <mesh geometry={nodes.wheel_backLeft_2.geometry}>
            <meshStandardMaterial {...hawkinsMaterials.brown} />
          </mesh>
        </group>
        <animated.mesh
          scale-x={cannonScale}
          scale-y={cannonScale}
          scale-z={cannonScale}
          geometry={nodes.barrel_2.geometry}
          position={[0, 0.45, -0.07]}
        >
          <meshStandardMaterial {...hawkinsMaterials.metal} />
        </animated.mesh>
      </group>
      <animated.group position-z={candyZ}>
        <Candy
          rotation-y={Math.PI / 2}
          position={[0, 0.45, -0.2]}
          scale={[0.6, 0.6, 0.6]}
          opacity={candyOpacity}
        />
      </animated.group>
    </group>
  );
}

useGLTF.preload("/models/springAnimationModel/cannon-mobile/model.gltf");
